server:
  port: '7100'

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${DISCOVERY_URL}

spring:
  application:
    name: file-storage
  profiles:
    active: deploy
  servlet:
    multipart:
      enabled: 'true'
      max-request-size: 215MB
      file-size-threshold: 2KB
      max-file-size: 200MB
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
file:
  uploadDir: ./images