server:
  port: '8080'

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${DISCOVERY_URL}

spring:
  application:
    name: file-storage
  profiles:
    #active: local
    active: dev
    #active: prod
  servlet:
    multipart:
      enabled: 'true'
      max-request-size: 215MB
      file-size-threshold: 2KB
      max-file-size: 200MB
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
file:
  uploadDir: ./images

# Google Cloud Vision API 설정
google:
  vision:
    api:
      enabled: true  # Google Cloud Vision API 활성화 여부
      threshold: LIKELY  # VERY_UNLIKELY, UNLIKELY, POSSIBLE, LIKELY, VERY_LIKELY 중 하나

logging:
  config: classpath:logback-spring.xml
  level:
    com:
      codism: info
    root: error
    org:
      hibernate:
        SQL: debug
    org.springframework.jdbc: DEBUG  # SQL 실행 로그 확인